### ISSUE TITLE
Installing the current project: chatgpt-memory (0.0.1)

### ISSUE THREAD

**Issue by newuhe** [continuum-llms/chatgpt-memory#21]
Installing the current project: chatgpt-memory (0.0.1) after `poetry install`, and throws "ModuleNotFoundError: No module named 'chatgpt_memory'
" when using simple_usage.py

**Comment by nps1ngh** [comment]
Hi,

could you please try running

```bash
$ poetry run python
>>> import chatgpt_memory
```

and check if this resolves the problem?

And then try

```bash
$ poetry run python simple_usage.py
```

?

If you want to use it globally then please install it with `pip`. See [this discussion](https://github.com/orgs/python-poetry/discussions/1135#discussioncomment-145739) for more info. Hope that resolves the issue!
