### ISSUE TITLE
Important Question / History by user

### ISSUE THREAD

**Issue by castroinvest** [continuum-llms/chatgpt-memory#23]
Congratulations on the code and creation.
I have doubts about the individualization of contexts.
I would like to know how I can make it so that each user who interacts with the application has their individualized message history, so that the conversation history of a user does not mix with that of the other.

**Comment by shahrukhx01** [comment]
Hi,
     The `conversation_id` parameter for the `converse` method from chatgpt client works as a identifier for each conversation. If you pass None for first time the method will return a unique new conversation id each time.

**Comment by castroinvest** [comment]
Wow, very nice man!
would you be available for a little freelance?
I really want to build a chatbot for people who live in nursing homes. And they're alone, with no people to talk to.

The elderly would describe how they want their virtual friend, and this virtual friend will respond according to the message history and the context of the described profile.

So I'm thinking of creating an api that receives the id of the elderly person as a parameter, if the id exists he can start interacting, if it doesn't exist he registers the profile and starts using it. And it would also have to have the option to change the profile of the virtual friend.

What do you think?
