### ISSUE TITLE
Error loading ASGI app. Could not import module "rest_api"

### ISSUE THREAD

**Issue by jairodriguez** [continuum-llms/chatgpt-memory#26]
Any idea why I am getting this error?

Any help is greatly appreciated.

**Comment by shahrukhx01** [comment]
Could you please specify the path at which you run the ‘uvicorn’ command? It needs to be run in the directory where ‘rest_api.py’ is located.

**Comment by ogoldberg** [comment]
agreed that this seems like you are perhaps in the wrong directory.
